### ISSUE TITLE
Unable to Build Web-UI 

### ISSUE THREAD

**Issue by Jragoon** [rib/gputop#191]
Following the instructions for building the Web-UI, I kept encountering a problem on several machines. Whenever I ran this command: 
`meson . build-webui -Dwebui=true --cross=scripts/meson-cross/emscripten-docker-debug.txt`
I would receive [this error](https://pastebin.com/VbprserZ).

 I was able to get past the issue by using the command: 
`./emsdk activate sdk-1.37.27-64bit` after
`cd /opt/emsdk-portable && ./emsdk install sdk-1.37.27-64bit`

In my case, it was also that: 
`cp build-webui/gputop-ui/* gputop-ui/` should be: `cp -r build-webui/ui/* ui/`

**Comment by Jragoon** [comment]
I also found that: `cp build-webui/gputop-ui/* gputop-ui/` should be: `cp -r build-webui/ui/* ui/`

**Comment by djdeath** [comment]
Is there still an issue here?
It seems that you found out how to build the webui in the end.

Building stuff with emscripten is a bit tricky.
As you've found out the best option is to use the sdk and that specific version (you could run into issues with a different one), indeed you need to activate/install the sdk so that all of its dependencies are available. If the right version of LLVM isn't installed emscripten won't be able to generate wasm/asmjs code (which is the issue you ran into).

Here are the commands run on the CI to compile the webui : 
https://github.com/rib/gputop/blob/master/scripts/travis-ci-build.sh
And the commands to deploy it : 
https://github.com/rib/gputop/blob/master/scripts/deploy-demo-site.sh

**Comment by Jragoon** [comment]
Thanks! Yeah, the issue is resolved for me. I thought I would mention my issue here in case someone comes across something similar.

**Comment by djdeath** [comment]
Yeah thanks, I'll add your finding into the README.
